In [1]:
import numpy as np
a=np.array([1,1,2,3,4,5])
print(a)
print(type(a))

[1 1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
#3d array
c=np.array([[[1,2],[1,2]],[[1,2],[1,2]]])
print(c)

[[[1 2]
  [1 2]]

 [[1 2]
  [1 2]]]


In [3]:
#printing array dimension
x=np.array([1,2,3,4,5])
y=np.array([[1,2,3,4],[5,6,7,8]])
z=np.array([[[1,2],[1,2]],[[1,2],[1,2]]])
print(x)
print(y)
print(z)
print(x.ndim)
print(y.ndim)
print(z.ndim)

[1 2 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [1 2]]

 [[1 2]
  [1 2]]]
1
2
3


In [4]:
print(a[0])
print(a[3])

1
3


In [5]:
#printing speific array elements
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row',arr[0,1])


2nd element on 1st row 2


In [6]:
#array data type
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]] , dtype='f2')
print(arr[1,0,2])
print(arr.dtype)

9.0
float16


In [7]:
#slicing arrays
#1d array
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[4:6])
print(arr[3:])
print(arr[:5])

[2 3 4 5]
[5 6]
[4 5 6 7]
[1 2 3 4 5]


In [8]:
#slicing arrays
#2d array
y=np.array([[1,2,3,4],[5,6,7,8]])
print(y[1,1:4])
print(y[0,2:4])
print(y[0,3:])
print(y[1,:5])

[6 7 8]
[3 4]
[4]
[5 6 7 8]


In [9]:
#to make a copy of array
b = np.array([1,2,3,4,5,6])
c = b.copy()
b[0]=42

print(b)
print(c)

[42  2  3  4  5  6]
[1 2 3 4 5 6]


In [10]:
#to view the array
b = np.array([1,2,3,4,5,6])
c = b.view()
b[0]=42

print(b)
print(c)

[42  2  3  4  5  6]
[42  2  3  4  5  6]


In [11]:
#SHAPING ARRAY
y=np.array([[1,2,3,4],[5,6,7,8]])
print(y.shape)

(2, 4)


In [12]:
#reshaping array
y=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new = y.reshape(4,3)
print(new)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
#flattening the array
y=np.array([[1,2,3,4],[5,6,7,8]])
new = y.reshape(-1)
print(new)

[1 2 3 4 5 6 7 8]


In [14]:
#iterating array
#1d
arr = np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [15]:
#iterating array
#2d
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in arr:
    print(x)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [23]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
10


In [28]:
#easier method with out using for loop multipile times
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10


In [31]:
#joining numpy arrays
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [32]:
#joining 2D arrays along rows(axis=1)


[1 2 3 4 5 6]
